# Generated by Django 3.2.15 on 2022-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofile',
            name='addedby_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
