# Generated by Django 3.2.15 on 2022-10-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_mprofile_addedby_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofile',
            name='reference_tablestatus_fk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minstructor_tablestatus', to='profile_app.mreference'),
        ),
    ]
