# Generated by Django 3.2.15 on 2022-10-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_mprofile_reference_tablestatus_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprofile',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='mprofile',
            name='firstname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mprofile',
            name='lastname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
