# Generated by Django 3.2.15 on 2022-10-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_auto_20221017_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofile',
            name='birthday',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
