# Generated by Django 3.2.15 on 2022-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_alter_mprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
