# Generated by Django 3.2.15 on 2022-10-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_alter_mprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mprofile',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mprofile',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mprofile',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
