# Generated by Django 3.2.15 on 2022-10-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_auto_20221017_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mprofile',
            old_name='address',
            new_name='profile_address',
        ),
    ]
