# Generated by Django 3.2.15 on 2022-10-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_rename_address_mprofile_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mprofile',
            old_name='profile_address',
            new_name='address',
        ),
    ]
